cancervariants/fusor

- Pipfile
- fusor/fusor.py
- fusor/models.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
- setup.py
- tests/test_fusor.py
* Update vrs-python pin to >=0.7.2
> Update vrs-python requirement

- .github/workflows/checks.yml
- .github/workflows/close_issue.yml
would like to circle back and set up more robustly in a few days but in the interim, add the close_issue action
> ci: add issue close action

- .coveragerc
- examples/ewsr1.json
- examples/tpm3_ntrk1.json
- fusor/exceptions.py
- fusor/fusor.py
- fusor/models.py
- fusor/version.py
- setup.cfg
- tests/test_fusor.py
- tests/test_models.py
messed up the branches so... please look forgivingly upon that, and on the messiness of these commits
*  catch latest information model changes
* add checks on pydantic model examples
* clean up fusion constructors
* clean up testing configs
> feat: latest model updates

- fusor/models.py
- fusor/nomenclature.py
- tests/test_models.py
- tests/test_nomenclature.py
Added a little bit more test coverage on the nomenclature side as well.
> fix: misc nomenclature bugs

- Pipfile
- README.md
- fusor/fusor.py
- fusor/version.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
- tests/conftest.py
- tests/test_fusor.py
> build!: pin dependency versions + update readme

- fusor/examples/README.md
- fusor/nomenclature.py
- fusor/version.py
- tests/test_nomenclature.py
> fix: remove identifier prefixes from nomenclature

- fusor/fusor.py
- setup.cfg
catch up with breaking API changes
> build: update cool-seq-tool dependency

- fusor/models.py
- tests/test_fusor.py
- tests/test_models.py
E.g.
* ALK::ALK should fail
* reg_e_EH38E3121735@IGH::IGH should fail
* BCR::ABL1 should pass
* v::ALK should pass
> feat: validate multi gene requirement

- Pipfile
- fusor/fusor.py
- fusor/models.py
- fusor/version.py
- setup.cfg
- tests/conftest.py
- tests/test_fusor.py
- tests/test_models.py
> build!: upgrade to pydantic v2

- README.md
> chore: add zenodo badge

- pyproject.toml
- src/fusor/fusor.py
- tests/test_fusor.py
> build!: update cool-seq-tool version

- src/fusor/fusor.py
- src/fusor/nomenclature.py
- src/fusor/tools.py
In advance of #150 -- this PR makes a bunch of changes to docstrings regarding format. In #150 we'll probably do a lot of additional small tweaks but this is some rote work that doesn't need to happen in that PR so I'm putting it up as a separate commit now.
> docs: update docstring format

- src/fusor/__init__.py
> fix: use correct version number

- src/fusor/tools.py
This is a wrapper for functions provided in [Cool-Seq-Tool](https://coolseqtool.readthedocs.io/stable/install.html#check-data-availability) and the gene normalizer. Intended to support installation debugging.
> feat: add resource check

- src/fusor/tools.py
Reverts cancervariants/fusor#178
> Revert "feat: add resource check"

- src/fusor/tools.py
This is a wrapper for functions provided in [Cool-Seq-Tool](https://coolseqtool.readthedocs.io/stable/install.html#check-data-availability) and the gene normalizer. Intended to support installation debugging.
>  feat: add resource check 

- pyproject.toml
- src/fusor/fusor.py
- src/fusor/models.py
- tests/test_fusor.py
draft for now, pending additional changes and a new release for CST but feel free to review
> feat!: update tx segment with new cool-seq-tool structure changes

- pyproject.toml
> build: Update cool-seq-tool version

- src/fusor/translator.py
- tests/test_translators.py
> fix!: Remove coordinate correction from fusion catcher translator

- src/fusor/models.py
- tests/test_models.py
closes #222
- Creates `AnchoredReads` and `ReadData` models and adds models as attributes in the `TranscriptSegmentElement` and `AssayedFusion` classes
> feat: add AnchoredReads and ReadData models

- pyproject.toml
- src/fusor/examples/alk.json
- src/fusor/examples/bcr_abl1.json
- src/fusor/examples/bcr_abl1_expanded.json
- src/fusor/examples/ewsr1.json
- src/fusor/examples/ewsr1_elements_only.json
- src/fusor/examples/ewsr1_no_assay.json
- src/fusor/examples/ewsr1_no_causative_event.json
- src/fusor/examples/igh_myc.json
- src/fusor/examples/tpm3_ntrk1.json
- src/fusor/examples/tpm3_pdgfrb.json
- src/fusor/fusor.py
- src/fusor/models.py
- src/fusor/nomenclature.py
- src/fusor/tools.py
- src/fusor/translator.py
- tests/conftest.py
- tests/test_fusor.py
- tests/test_models.py
- tests/test_nomenclature.py
- tests/test_translators.py
closes #237 
- Updates the VRS-Python, gene-normalizer, and cool-seq-tool versions, replace the `Gene` class with `MappableConcept`
> build!: Update VRS-Python, gene normalizer, and cool-seq-tool versions

- src/fusor/fusion_caller_models.py
- src/fusor/harvester.py
- tests/fixtures/enfusion_test.csv
> fix!: Update EnFusion harvester

- .pre-commit-config.yaml
- pyproject.toml
- src/fusor/__init__.py
- src/fusor/harvester.py
- src/fusor/models.py
- src/fusor/nomenclature.py
- src/fusor/tools.py
- tests/conftest.py
- tests/test_fusion_matching.py
- tests/test_fusor.py
- tests/test_models.py
- tests/test_nomenclature.py
- tests/test_translators.py
It looks like I accidentally never did the January Ruff update for this repo, so this is a year's worth of changes. Almost entirely just formatting + a few logger calls with a little added detail.
> style: update ruff and precommit

- src/fusor/harvester.py
> fix!: Fix delimiter typo

- notebooks/evidence_matching/fusion_evidence_matching.ipynb
> fix!: Remove value from evidence matching notebook

- notebooks/evidence_matching/fusion_evidence_matching.ipynb
- src/fusor/harvester.py
- tests/test_harvesters.py
> feat!: Load in accepted fusion variants directly in CIViC harvester
