cancervariants/fusor

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg
* Unpin jsonschema.
VRS-Python is now updated to handle this dependency issue, so we should unpin here and use their requirements.
=> Unpin jsonschema

examples/exhaustive_example.json, fusor/exceptions.py, fusor/fusor.py, fusor/models.py, tests/test_fusor.py
* Raise IDTranslationException upon failed sequence ID translation attempt
* Don't update components in `add_translated_sequence_id` if translation fails (fix #66)
=> Handle failed sequence ID translation by raising exception

examples/alk.json, examples/epcam_msh2.json, examples/exhaustive_example.json, examples/minimal_example.json, examples/tpm3_ntrk1.json, examples/tpm3_pdgfrb.json, fusor/fusor.py, fusor/models.py, tests/test_fusor.py, tests/test_models.py
Partially out of thoughtlessness and laziness, I'd been leaving type values out of some objects and had used inconsistent naming/case patterns. This updates FUSOR objects to be consistent with Pascal Case (as used in VRS/VRSATILE) and ensures that type values are given for all objects.
=> Fix: make type values consistent

examples/README.md, fusor/nomenclature.py, fusor/version.py, tests/test_nomenclature.py
closes #90 
Nomenclature [here](https://fusions.cancervariants.org/en/draft-1/nomenclature.html?highlight=junction#junction-components)
=> fix: junction nomenclature to remove additional _

fusor/models.py, fusor/version.py, tests/test_models.py
VRSATILE technically allows two different JSON structures for defining gene concept IDs, this catches the second way for the "must have multiple genes" model validation
=> fix: catch alternate gene descriptor structure

fusor/examples/__init__.py, fusor/examples/ewsr1_elements_only.json, fusor/examples/ewsr1_no_assay.json, fusor/examples/ewsr1_no_causative_event.json, fusor/fusor.py, fusor/models.py, tests/test_nomenclature.py
in my original PR, I did not address an issue where in nomenclature generation, the fusion's assay is assumed to always exist, so this would result in fusor throwing an exception when no assay is provided. 
In this PR, I added some short circuiting logic to avoid that exception being thrown and also added unit tests to check for proper nomenclature generation when assay or causative event are not provided.
=> feat: relax requirements on minimum information model

.github/workflows/checks.yml, .pre-commit-config.yaml, fusor/__init__.py, fusor/examples/__init__.py, fusor/exceptions.py, fusor/fusor.py, fusor/models.py, fusor/nomenclature.py, fusor/tools.py, pyproject.toml, setup.cfg, setup.py, tests/conftest.py, tests/test_fusor.py, tests/test_models.py, tests/test_nomenclature.py, tests/test_tools.py
close #137 
purely stylistic change -- removes the `black` dependency and uses Ruff's formatter instead.
=> style: use ruff for formatting

pyproject.toml, src/fusor/fusor.py, tests/conftest.py
@katiestahl and I have both noticed that FUSOR tests can hang on the FTP callout to check that the MANE summary file is up to date. This PR makes `Cool-Seq-Tool` injectable and, in test, uses the `force_local_files` arg to suppress that recency check.
=> feat!: enable cool-seq-tool injection

src/fusor/examples/bcr_abl1.json, src/fusor/examples/bcr_abl1_expanded.json, src/fusor/fusor.py, src/fusor/models.py, tests/conftest.py, tests/test_fusor.py, tests/test_models.py
close #152 
there's a corresponding PR up on the docs as well 
we don't _have_ to change the field name from `r_` to `reading_` but I think it's an unnecessary contraction so now's a good time to change it, if we're up for it
=> feat!: add reading frame to assayed fusions

pyproject.toml, src/fusor/fusor.py, src/fusor/models.py
to ensure correct classes are always being validated
This fixes the validation error we were having with pydantic versions above `2.4.2`, when constructing a fusion, some of the structural elements were not being associated with the correct class type and causing validation errors (ie; a created TemplatedSequenceElement was being validated with TranscriptSegmentElement validators when calling `fusor.fusion(structure....` because pydantic was incorrectly resolving the class type or not using it at all)
This seems to be backwards compatible with other 2.x pydantic versions. (I checked with 2.8.2 (most recent) and with 2.4.2). This only won't work properly with pydantic versions before 1.8, where the discriminator was introduced.
=> fix: update structural elements with discriminator 

src/fusor/fusor.py, src/fusor/nomenclature.py, tests/test_nomenclature.py
Not sure if this is really a meaningful change, but I thought it was weird that the `nomenclatures` module contained code for generating some of the nomenclature subcomponents but not the entire nomenclature string. This PR pulls that code out of FUSOR and puts it into the nomenclature module.
As a side note, a lot of stuff in FUSOR is named very weirdly. It would be annoying to rename but we have a lot of methods that have noun phrase names rather than "doing" names.
Would like to get this merged before docs PR.
=> feat: add independent nomenclature method

src/fusor/models.py
So this comment: https://github.com/cancervariants/fusion-curation/pull/314#issuecomment-2309960695 seems to have uncovered this issue. I don't really know why/how this ever worked? You can see on line 514, it's implied that this is an object, so I'm not sure why on line 516 we're attempting to subscript the object. 
I could be totally off on this, but I'm going to open this PR just in case! This could be a good discussion :D
=> fix: attempting to subscript an object

src/fusor/fusor.py, src/fusor/models.py, src/fusor/tools.py, tests/test_fusor.py, tests/test_models.py, tests/test_tools.py
close #187 
I think this is the only place I need to make changes, since the rest return custom messages. This extracts only the message from the error so we don't get all of the pydantic validation error extra stuff.
=> fix: return correct message when validation error occurs

src/fusor/translator.py, tests/test_translators.py
Closes #203  
Notes: This translator includes a variable that tells us if a transcript segment starts or ends at breakpoint, so new logic was added to take this into account. 
From Arriba:
direction1 and direction2 : These columns indicate the orientation of the fusion breakpoints. A value of downstream means that the fusion partner is fused downstream of the breakpoint, i.e., at a coordinate higher than the breakpoint.In other words, the supporting split reads are right-clipped. A value of upstream means the partner is fused at a coordinate lower than the breakpoint. In other words, the supporting split reads are left-clipped. When the prediction of the strands or of the 5' gene fails, this information gives insight into which parts of the fused genes are retained in the fusion.
This …
=> feat!: change arriba fusion detection algorithm input parameters

src/fusor/translator.py, tests/test_translators.py
closes #205 
- Add checks for examining if the gene fusion event has biological meaning (using the `sv_ort` column) and if multiple gene symbols are listed for a fusion partner (one gene symbol is expected)
- The documentation/associated metadata does not highlight any good ways to resolve this ambiguity, so for now I added code to skip fusion calls where this happens
=> feat!: change CICERO fusion detection algorithm input parameters

src/fusor/translator.py, tests/test_translators.py
Closes #209 
- The GENIE data is unstructured compared to other callers. For example, GENIE is inconsistent in what it describes as the 5'gene fusion partner and 3'gene fusion partner. However, in testing different fusions, I've seen the genomic breakpoints line up with the annotations provided by GENIE, so I think our approach is generally correct.
Note: I'm not sure due to rules regarding the GENIE data if I'm allowed to copy those examples here, so let me know if you'd like to see them and I can send them over
=> feat!: change Genie fusion detection algorithm input parameters

src/fusor/translator.py, tests/test_translators.py
closes #213 
Once the gene fusion partners are normalized, check to ensure that the resulting symbols are different. The VICC specification requires the partners to be different to be a valid fusion.
=> fix: Add gene symbol check in translator methods

src/fusor/models.py, tests/test_models.py
closes #218 
I'm pretty sure that the `BreakpointCoverage` class belongs at the `TranscriptSegment` level and that the `ContigSequence` class belongs at the `AssayedFusion` level. I'm unsure if the Split and Spanning Reads class would belong at the transcript or fusion level (may depend on how this data is reported by the specific fusion detection algorithm). I will go over this question with @ahwagner and modify in a separate PR
=> feat: Add new metadata classes for AssayedFusion events

src/fusor/translator.py, tests/test_translators.py
closes #220 
- We increment the breakpoints by 1 in the translator tests when we know `alt_start_i` is being used to compute the exon offset and when we have residue coordinates
- All my tests are working but I notice a lot of warnings (4154) which I think may be due to updating my python version. Is this something I need to correct?
=> feat!: Add support for coordinate type in translators

src/fusor/models.py, src/fusor/translator.py, tests/test_translators.py
closes #247 
- Adds a VICC Nomenclature string to each translated fusion event. This covers both `AssayedFusion` and `CategoricalFusion` objects.
=> feat: Add VICC Nomenclature string to each translated fusion event

src/fusor/nomenclature.py, tests/test_nomenclature.py
=> fix!: Remove (::) divider for inferred fusions

src/fusor/tools.py
FUSOR's `fusor.tools.check_data_resources` method crashes if the gene normalizer database isn't available, rather than reporting that it isn't available via `gene_normalizer=False`. This is because the `create_db()` call is outside the exception handling try/catch block.
I fixed this by moving the `create_db()` call into the try/catch block so that the exception would be caught and the status reported as expected.
<details>
<summary>Output before</summary>
Unhandled exception results in no status object being returned:
```
>  ./test-fusor.py check                                                                                                              
Traceback (most recent call last):
File "/Users/zxw016/dev/wagner/./test-fusor.py", line 150, in <module>
main()
~~~~^^
File …
```
=> fix: Catch errors from create_db when gene normalizer db unavailable

src/fusor/harvester.py, tests/test_harvesters.py
This PR modifies `Harvester` to add a `load_record_table` function which assembles a list of `FusionCallerRecord` objects
which contain the original untranslated fusion caller output (in `source`), the translated FUSOR output (in `annotated`) and any errors that may have happened while translating that call (in `annotation_errors`).
Since this is very similar to the behavior of `load_records`, I refactored `load_records` to call `load_record_table` and then filter down the output to only the annotated records, to preserve the original behavior while minimizing redundant code.
Resolves #302
=> feat: add harvester method to return both translated and untranslated records

src/fusor/models.py, tests/test_models.py
=> feat!: Remove `cls.__name__` comparator for `AbstractFusion` class

src/fusor/models.py, tests/test_models.py
* Ensures consistent validation across subclasses
Noticed this issue in a downstream app (fusion-curation) where validating the raw input data was causing tests to fail.
=> refactor: change model_validator mode='before' to mode='after'
